
server:
  port: 8088
spring:
  application:
    name: config
  cloud:
    config:
      discovery:
        enabled: true
      server:
        git:
          uri:
          username: haidilaohotpot
          password:
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/
jasypt:
  encryptor:
    password: keys

